- name: Jenkins Setup
  hosts: all
  tasks:
   - name: Install required softwares.
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: openjdk-8-jdk, b: yes}
      - {a: git, b: no}
      - {a: maven, b: no}
   - name: Download Jenkins URL
     get_url:
      url: https://get.jenkins.io/war-stable/2.319.2/jenkins.war
      dest: /home/ubuntu
   - name: Run Jenkins
     shell: 
      'java -jar jenkins.war'
